/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * 
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user guide at https://docs.gradle.org/4.10.2/userguide/multi_project_builds.html
 */

rootProject.name = "learn-kotlin"

include("greeting-java")
include("greeting-kotlin")
include("greeter")
include("01-hello-kotlin")
include("02-variables")
include("03-conditionals")
include("04-functions")
include("05-null-safety")
include("06-exceptions")
include("07-strings")
include("08-numbers")
include("09-std-functions")