
rootProject.name = "learn-kotlin"

include("greeting-java")
include("greeting-kotlin")
include("greeter")
include("01-hello-kotlin")
include("02-variables")
include("03-conditionals")
include("04-functions")
include("05-null-safety")
include("06-exceptions")
include("07-strings")
include("08-numbers")
include("09-std-functions")
include("10-collections")
include("11-oop")
include("12-generics")
include("13-extensions")
include("14-coroutines")
include("16-dsl")